import { Poppins } from "next/font/google";
import "./globals.css";
import AppShell from "../components/AppShell";

const poppa = Poppins({
  weight: ["100","200","400","600", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "GLOBAL SOFT REPORT SYSTEM",
  description: "Generated by GLOBAL SOFT SOLUTION (PVT).LTD",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppa.className}>
        <AppShell>
          {children}
        </AppShell>
      </body>
    </html>
  );
}
